name: UART test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  uart-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files (debug)
        run: dir
        shell: cmd

      - name: Run UART toggle test
        run: .\ESP32_UART_Toggle.bat
        shell: cmd
